### ISSUE TITLE
Rejoin channel on reconnect

### ISSUE THREAD

**Issue by nivex** [acomminos/Plumble#147]
Would like to be rejoined to the channel I was in when a reconnect occurs.

Use case: Sometimes I lose WiFi for a few seconds, especially when moving between APs. This causes a reconnect, after which I am placed back in Root.

**Comment by israuor** [comment]
I guess that has nothing to do with Plumble. It's server related. Are you using a certificate and are you registered on the server?

**Comment by acomminos** [comment]
This functionality is provided by the Mumble protocol for registered users on a server. I don't think it's particularly useful to add support for the rare case in which a user may not be permitted to register, considering that the desktop client doesn't.

**Comment by dofl** [comment]
@acomminos. I'm using the limited version of Murmur, [uMurmur](http://umurmur.net/). This does not have a user database and does not allow for user registration. I'm using Plumble to connect motorcycle headsets to a portable WiFi so that the group can speak to each other. It happens that the WiFi connection drops and that the user must manually connect back, which is impossible during a drive.
